server:
  port: 10002
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///guns?characterEncoding=utf8&serverTimezone=UTC
    username:
    password:
mybatis:
  mapper-locations: classpath:mapping/*xml
  type-aliases-package: com.meng.config_ssm.pojo
