server:
  port: 10002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/withmycarmember?characterEncoding=utf8&serverTimezone=UTC
    username: wanger
    password: 19970521
mybatis:
  mapper-locations: classpath:mapping/*xml
  type-aliases-package: com.meng.config_ssm.pojo
